"""empty message

Revision ID: 180298687e87
Revises: 
Create Date: 2023-08-29 20:39:08.195735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '180298687e87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_types')
    op.drop_table('seasons')
    op.drop_table('teams')
    op.drop_table('photos')
    op.drop_table('rounds')
    op.drop_table('games')
    op.drop_table('events')
    op.drop_table('scores')
    op.drop_table('item_catalog')
    op.drop_table('cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.BINARY(length=36), nullable=False),
    sa.Column('city_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('city_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('item_catalog',
    sa.Column('item_id', sa.BINARY(length=36), nullable=False),
    sa.Column('item_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('item_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('cost', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preview_photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('booking_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scores',
    sa.Column('team_id', sa.BINARY(length=36), nullable=False),
    sa.Column('round_id', sa.BINARY(length=36), nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], name='scores_ibfk_2'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='scores_ibfk_1'),
    sa.PrimaryKeyConstraint('team_id', 'round_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('events',
    sa.Column('event_id', sa.BINARY(length=36), nullable=False),
    sa.Column('event_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('event_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('cost', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preview_photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('event_time', mysql.DATETIME(), nullable=True),
    sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('booking_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('city_id', sa.BINARY(length=36), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='events_ibfk_1'),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('games',
    sa.Column('game_id', sa.BINARY(length=36), nullable=False),
    sa.Column('game_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('game_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('preview_photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('game_time', mysql.DATETIME(), nullable=True),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('score_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('booking_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('city_id', sa.BINARY(length=36), nullable=False),
    sa.Column('season_id', sa.BINARY(length=36), nullable=False),
    sa.Column('game_type_id', sa.BINARY(length=36), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='games_ibfk_1'),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.game_type_id'], name='games_ibfk_3'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], name='games_ibfk_2'),
    sa.PrimaryKeyConstraint('game_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rounds',
    sa.Column('round_id', sa.BINARY(length=36), nullable=False),
    sa.Column('round_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('game_id', sa.BINARY(length=36), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name='rounds_ibfk_1'),
    sa.PrimaryKeyConstraint('round_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('photos',
    sa.Column('game_id', sa.BINARY(length=36), nullable=False),
    sa.Column('preview_photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('photo_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name='photos_ibfk_1'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teams',
    sa.Column('team_id', sa.BINARY(length=36), nullable=False),
    sa.Column('team_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.BINARY(length=36), nullable=False),
    sa.Column('season_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('season_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('preview_photo', mysql.LONGBLOB(), nullable=True),
    sa.Column('season_time', mysql.DATETIME(), nullable=True),
    sa.Column('city_id', sa.BINARY(length=36), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], name='seasons_ibfk_1'),
    sa.PrimaryKeyConstraint('season_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('game_types',
    sa.Column('game_type_id', sa.BINARY(length=36), nullable=False),
    sa.Column('game_type_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('game_type_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
